name: ${pluginName}
version: ${version}
api-version: '${bukkitApiVersion}'
main: 'xyz.icetang.lib.openconfigeditor.${pluginName}'
author: Icetang0123
libraries:
  - xyz.icetang.lib:icemmand-core:${icemmandVersion}
  - io.github.monun:invfx-core:3.3.2